include:
  - project: 'devops/ci-cd/deploy'
    ref: develop
    file: '/ci/.gitlab-ci-java-migration-new.yml'

variables:
  NAMESPACE: 'devops-utils'
  SKIP_BUILD: "true"  # Если "true", то мы хотим выполнить наш override

stages:
  - build

build:
  stage: build # данная стейдж переписывает билд из основного пайплайна
  rules:
    - if: '$SKIP_BUILD == "true"'
      when: always    # Если переменная установлена, выполняем наш job
    - when: never     # Иначе job не выполняется
  script:
    - echo "Executing local build override because SKIP_BUILD is true"
